version: "3"
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: Cleix-1002
      POSTGRES_DB: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql/data
